apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docuchat
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true
spec:
  project: default
  source:
    repoURL: https://github.com/mmostafa74/cluster-argocd.git
    targetRevision: main
    path: docuchat
    helm:
      valuesObject:
        ingress:
          enabled: true
          className: "traefik"
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
            - host: docuchat.resha.vaza.dev
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: docuchat-tls
              hosts:
                - docuchat.resha.vaza.dev
        service:
          type: ClusterIP
          port: 8501
        containerPort: 8501
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          - name: OPENROUTER_API_KEY
            valueFrom:
              secretKeyRef:
                name: docuchat-secret
                key: OPENROUTER_API_KEY
  destination:
    server: https://kubernetes.default.svc
    namespace: docuchat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
