apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-chatbot
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: CreateNamespace=true
spec:
  project: default
  source:
    repoURL: https://github.com/mmostafa74/cluster-argocd.git
    targetRevision: main
    path: llm-chatbot
    helm:
      valuesObject:
        ingress:
          enabled: true
          className: "traefik"
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
            - host: llm-chatbot.resha.vaza.dev
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: llm-chatbot-tls
              hosts:
                - llm-chatbot.resha.vaza.dev
        service:
          type: ClusterIP
          port: 8501
        containerPort: 8501
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
          secretName: llm-chatbot-env
          mountPath: /app/.env
  destination:
    server: https://kubernetes.default.svc
    namespace: llm-chatbot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
